var _dynamicParams = {
    config: {
      wheelUX: "0",
      totalSlices: 8,
      distanceDeg: 45,
      defaultStartDeg: 270,
      borderSlice: 5,
      sliceWidth: 30,
      graphicOption: 1,
      brandLogo: "img/brand.png",
      backgroundColor: "#337ab7",
      allowSound: true,
      anims: { fallingSnow: false, flame: false },
    },
    jsonData: [
      { value: "100$ دولار", imageUrl: "img/reward0.png" },
      { value: "ابل واتش SE 2022", imageUrl: "img/reward4.png" },
      { value: "ماك بوك برو 2022", imageUrl: "img/reward3.png" },
      { value: "بلايسايشن 5", imageUrl: "img/reward2.png" },
      { value: "ايباد برو 2022", imageUrl: "img/reward5.png" },
      { value: "تلفاز سامسونج سيريس 7", imageUrl: "img/reward6.png" },
      { value: "ايربودز برو 2022", imageUrl: "img/reward7.png" },
      { value: "ايفون 14 بور ماكس", imageUrl: "img/reward1.png" },
    ],
    anims: { fallingSnow: false },
  };
