var _dynamicParams = {
    config: {
      wheelUX: "0",
      totalSlices: 8,
      distanceDeg: 45,
      defaultStartDeg: 270,
      borderSlice: 5,
      sliceWidth: 30,
      graphicOption: 1,
      brandLogo: "img/brand.png",
      backgroundColor: "#337ab7",
      allowSound: true,
      anims: { fallingSnow: false, flame: false },
    },
    jsonData: [
      { value: "100$ USD", imageUrl: "img/reward0.png" },
      { value: "Apple Watch SE 2022", imageUrl: "img/reward4.png" },
      { value: "Mac Book Pro 2022", imageUrl: "img/reward3.png" },
      { value: "Playstation 5", imageUrl: "img/reward2.png" },
      { value: "IPad Pro 2022", imageUrl: "img/reward5.png" },
      { value: "SAMSUNG Series 7 tv", imageUrl: "img/reward6.png" },
      { value: "Air Bods Pro 2022", imageUrl: "img/reward7.png" },
      { value: "Iphone 14 Pro max", imageUrl: "img/reward1.png" },
    ],
    anims: { fallingSnow: false },
  };
